In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
# for a one dimensional array we can access data in a very similar way to using lists in python
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [7]:
vv = np.random.random((5,4))

In [8]:
vv

array([[0.98021335, 0.01872588, 0.75305147, 0.37027532],
       [0.41585049, 0.87499334, 0.15837522, 0.27963443],
       [0.95055412, 0.00588049, 0.60617568, 0.01325651],
       [0.25564767, 0.64884134, 0.71291884, 0.37611487],
       [0.29710125, 0.9681563 , 0.74663821, 0.90080234]])

In [9]:
# when taking data from an array which is two dimensions specify first the row then column 
vv[0,0]

0.9802133537507944

In [10]:
vv[4,3]

0.9008023382253677

In [12]:
# we can create a list of lists however we can't then specifcy data in the same format
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
ll[1,2]

TypeError: list indices must be integers, not tuple

In [14]:
# instead we first need to identify the first container then specify where in it is
ll[1][2]

6

In [15]:
# slicing works in a very similar way to basic python
v[2:4]

array([ 5. ,  7.5])

In [16]:
# for 2D arrays we can slice in one or both dimensions
vv[2:5,1]

array([ 0.55486179,  0.57444187,  0.1354475 ])

In [17]:
vv[2:5,1:2]

array([[ 0.55486179],
       [ 0.57444187],
       [ 0.1354475 ]])

In [18]:
vv[2:-1,:]

array([[ 0.87007385,  0.55486179,  0.52878119,  0.9913901 ],
       [ 0.40446365,  0.57444187,  0.77248462,  0.2901253 ]])

In [20]:
vv[:,::2]

array([[ 0.09137921,  0.39884184],
       [ 0.61637695,  0.023984  ],
       [ 0.87007385,  0.52878119],
       [ 0.40446365,  0.77248462],
       [ 0.25235129,  0.68302613]])

In [11]:
# if we create a new array by slicing then edit it's data then we end up editing the original array 
# NOTE this is different to base python so BE CAREFUL!!!!
v2 = v[2:4]
v2

array([5. , 7.5])

In [12]:
v2[0] = 0

In [13]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [14]:
# if we need a copy of an array we need to explicitally say it, this will prevent editing the original copy
v3 = v[2:4].copy()

In [15]:
v3[0] = 1

In [16]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [17]:
# we can use a list when specifying an array to only get back certain values from it
v[[1,2,3]]

array([2.5, 0. , 7.5])

In [23]:
# we can also use a specific operator to test the values in the array, e.g. whether they are larger than 0
bool_index = v > 0
bool_index

array([False,  True, False,  True,  True])

In [19]:
# we can then use this as a filter to make an array smaller 
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [26]:
# this takes all the elements larger than 0.5 in the previous array and multiplies them by 2
# note that if you run this code multiple times it gets larger and larger as you are editing the real values!
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [27]:
vv

array([[7.84170683e+00, 1.87258802e-02, 6.02441178e+00, 3.70275319e-01],
       [4.15850495e-01, 6.99994675e+00, 1.58375222e-01, 2.79634426e-01],
       [7.60443298e+00, 5.88049252e-03, 4.84940542e+00, 1.32565130e-02],
       [2.55647675e-01, 5.19073073e+00, 5.70335068e+00, 3.76114872e-01],
       [2.97101246e-01, 7.74525039e+00, 5.97310571e+00, 7.20641871e+00]])